name: ai
channels:
    - conda-forge
    - defaults
dependencies:
    - python=3.7
    - jupyter
    - nbconvert=5.6.1
    - jupyter_contrib_nbextensions
    - graphviz
    - python-graphviz
    - ply
    - ipycanvas
    - matplotlib
    - seaborn
    - tensorflow
    - scikit-learn
    - nltk
    - pip:
        - jedi==0.17.2
        - python-chess